import React from 'react';
import ReactMarkdown from 'react-markdown';
import { ArrowLeft, RefreshCw, Sparkles, Tag } from 'lucide-react';
import { ImageFile } from '../types';

interface AnalysisViewProps {
  image: ImageFile;
  result: string;
  onReset: () => void;
}

export const AnalysisView: React.FC<AnalysisViewProps> = ({ image, result, onReset }) => {
  return (
    <div className="animate-fade-in pb-20">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
        
        {/* Navigation / Actions */}
        <div className="flex items-center justify-between mb-8">
          <button 
            onClick={onReset}
            className="flex items-center text-slate-400 hover:text-white transition-colors group"
          >
            <div className="p-2 rounded-full bg-slate-800 group-hover:bg-slate-700 mr-3 border border-slate-700 transition-all">
              <ArrowLeft className="w-5 h-5" />
            </div>
            <span className="font-medium">Analyze Another</span>
          </button>
          
          <div className="flex items-center space-x-2 text-indigo-400 bg-indigo-500/10 px-4 py-2 rounded-full border border-indigo-500/20">
            <Sparkles className="w-4 h-4" />
            <span className="text-sm font-semibold tracking-wide uppercase">Analysis Complete</span>
          </div>
        </div>

        <div className="grid grid-cols-1 lg:grid-cols-12 gap-8 lg:gap-12">
          
          {/* Left Column: Image */}
          <div className="lg:col-span-5 space-y-6">
            <div className="sticky top-24 space-y-6">
              <div className="relative rounded-2xl overflow-hidden shadow-2xl shadow-black/50 border border-slate-700 bg-slate-800">
                <img 
                  src={image.preview} 
                  alt="Product analysis subject" 
                  className="w-full h-auto object-cover max-h-[600px]"
                />
                <div className="absolute inset-0 bg-gradient-to-t from-slate-900/80 to-transparent opacity-60"></div>
                <div className="absolute bottom-4 left-4 right-4">
                  <div className="flex items-center space-x-2 text-xs text-white/80 font-mono">
                    <Tag className="w-3 h-3" />
                    <span>SOURCE IMAGE</span>
                  </div>
                </div>
              </div>

              {/* Quick Actions (Future expansion) */}
              <div className="p-4 rounded-xl bg-slate-800/50 border border-slate-700/50 backdrop-blur-sm">
                <h4 className="text-sm font-semibold text-slate-300 mb-2">Confidence Score</h4>
                <div className="w-full bg-slate-700 rounded-full h-2 mb-1">
                  <div className="bg-indigo-500 h-2 rounded-full w-[92%]"></div>
                </div>
                <div className="flex justify-between text-xs text-slate-500">
                  <span>Visual Clarity</span>
                  <span>High (92%)</span>
                </div>
              </div>
            </div>
          </div>

          {/* Right Column: Content */}
          <div className="lg:col-span-7">
            <div className="bg-slate-800/40 border border-slate-700/50 rounded-2xl p-6 sm:p-10 shadow-xl backdrop-blur-sm">
              <div className="prose prose-invert max-w-none markdown-body">
                <ReactMarkdown>{result}</ReactMarkdown>
              </div>
              
              <div className="mt-10 pt-6 border-t border-slate-700/50 flex flex-col sm:flex-row sm:items-center sm:justify-between text-slate-400 gap-4">
                <div className="text-xs">
                  Generated by Gemini 2.5 Flash • {new Date().toLocaleDateString()}
                </div>
                <button 
                   onClick={onReset}
                   className="flex items-center justify-center space-x-2 px-4 py-2 bg-indigo-600 hover:bg-indigo-500 text-white rounded-lg transition-all text-sm font-medium shadow-lg shadow-indigo-500/25"
                >
                  <RefreshCw className="w-4 h-4" />
                  <span>Start New Analysis</span>
                </button>
              </div>
            </div>
          </div>

        </div>
      </div>
    </div>
  );
};